// Sherwood Forest Timeline Data
// Each event: { id, year, yearLabel, title, body, tags[], era, conflict, source, sourceUrl }

const TIMELINE_EVENTS = [
  {
    id: 1,
    year: 958,
    yearLabel: "958 AD",
    title: "First Written Record: 'Sciryuda'",
    body: "The earliest written mention of Sherwood appears in an Anglo-Saxon document, recording the forest as <em>Sciryuda</em> — \"the woodland belonging to the shire.\" This suggests a pre-existing tradition of communal or shire ownership long before Norman forest law.",
    tags: ["royal", "commons"],
    era: "saxon",
    conflict: false,
    source: "Nottinghamshire County Council",
    sourceUrl: "https://www.nottinghamshire.gov.uk/culture-leisure/country-parks/history-of-sherwood-forest-robin-hood-and-major-oak"
  },
  {
    id: 2,
    year: 1066,
    yearLabel: "1066",
    title: "Norman Conquest: Forest Law Imposed",
    body: "William the Conqueror declares Sherwood a Royal Hunting Forest. Norman Forest Law replaces Anglo-Saxon custom. Deer and timber become royal property; killing deer is punishable by blinding or castration. The local population — peasants, freemen, and commoners — lose free access to resources they had depended on for generations.",
    tags: ["royal", "commons", "enclosure"],
    era: "norman",
    conflict: true,
    source: "Sherwood Forest — Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Sherwood_Forest"
  },
  {
    id: 3,
    year: 1086,
    yearLabel: "1086",
    title: "Domesday Book: ~19,000 Acres Recorded",
    body: "The Domesday Book records Sherwood as covering roughly 19,000 acres (7,800 ha) of woodland and heath subject to Forest Law — approximately a quarter of Nottinghamshire. The survey documents the systematic dispossession of English landholders by Norman lords.",
    tags: ["royal"],
    era: "norman",
    conflict: false,
    source: "Sherwood Forest — Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Sherwood_Forest"
  },
  {
    id: 4,
    year: 1100,
    yearLabel: "c. 1100",
    title: "Henry I Expands Forest Law & Jurisdiction",
    body: "Henry I dramatically extends Forest Law across Nottinghamshire north and west of the River Trent. Punishments are harsh and arbitrary. Forest courts (Attachment Courts, Forest Eyre) at Edwinstowe, Mansfield, Linby, and Calverton become instruments of royal revenue extraction — fines for trespassing, gleaning, or keeping dogs near the forest.",
    tags: ["royal", "commons"],
    era: "norman",
    conflict: true,
    source: "Nottinghamshire History",
    sourceUrl: "http://www.nottshistory.org.uk/articles/tts/tts1946/sherwood1.htm"
  },
  {
    id: 5,
    year: 1154,
    yearLabel: "1154",
    title: "Sherwood First Named as Royal Hunting Preserve",
    body: "The first explicit record of Sherwood as a <em>forest</em> in the legal sense — a royal hunting preserve subject to Forest Law — dates to 1154, the reign of Henry II. This confirms its royal status was established at least under Henry I. Henry II also issues the Assize of the Forest (1184), codifying brutal forest law nationwide.",
    tags: ["royal"],
    era: "norman",
    conflict: false,
    source: "Sherwood Forest History (World Anvil synthesis)",
    sourceUrl: "https://www.worldanvil.com/w/fabula-mundi-barwickian/a/sherwood-forest-organization"
  },
  {
    id: 6,
    year: 1199,
    yearLabel: "1199–1216",
    title: "King John & the Expansion of Forest Tyranny",
    body: "King John aggressively expands Forest Law as a revenue mechanism. He extends royal forest jurisdiction across almost all of Nottinghamshire north of the Trent. The oppressive enforcement — arbitrary amercements, extortion by foresters and sheriffs — is a direct catalyst for baronial uprising. The Sheriff of Nottingham's role in this era forms the historical core of the Robin Hood legend.",
    tags: ["royal", "commons", "robin-hood"],
    era: "norman",
    conflict: true,
    source: "Sherwood Forest History Blog — Magna Carta",
    sourceUrl: "https://sherwoodforesthistory.blogspot.com/2012/10/magna-carta-forest-charter-and-sherwood.html"
  },
  {
    id: 7,
    year: 1215,
    yearLabel: "1215",
    title: "Magna Carta: Forest Clauses Limit Royal Power",
    body: "The barons force King John to seal Magna Carta at Runnymede. The charter contains explicit forest clauses (including clauses 44, 47, 48) designed to curtail royal forest abuses — limiting amercements, requiring investigation of \"evil customs,\" and promising to disafforest lands seized since Henry II's reign. Sherwood Forest's commons-vs-crown tensions are a direct backdrop. The Major Oak's hollow is mythically associated with Robin Hood and his men — 1216 in local legend.",
    tags: ["royal", "commons", "robin-hood"],
    era: "norman",
    conflict: true,
    source: "Edwinstowe Historical Society",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/"
  },
  {
    id: 8,
    year: 1217,
    yearLabel: "1217",
    title: "Charter of the Forest: Commoners' Rights Guaranteed",
    body: "A dedicated <em>Carta de Foresta</em> (Charter of the Forest) — sometimes called the 'forgotten twin' of Magna Carta — is sealed, guaranteeing commoners' rights within royal forests. It abolishes execution and mutilation as forest punishments, limits the extent of the royal forest, and affirms rights of <em>pannage</em> (pig-feeding on acorns), <em>turbary</em> (peat-cutting), <em>firebote</em> (firewood), and <em>herbage</em> (grazing). It remains on the statute books until 1971.",
    tags: ["royal", "commons"],
    era: "medieval",
    conflict: false,
    source: "Magna Carta 800th Trust",
    sourceUrl: "https://magnacarta800th.com/papers/forests-the-magna-carta-and-the-new-commons-some-thoughts-for-the-forest-panel/"
  },
  {
    id: 9,
    year: 1218,
    yearLabel: "1218–1300",
    title: "Perambulations: Boundary Disputes &amp; Disafforestation",
    body: "A series of formal perambulations (boundary surveys) — 1218, 1232, 1300 — attempt to define the limits of Sherwood. The 1232 and 1300 surveys are identical, suggesting stable medieval boundaries. The Forest Charter of 1217 triggers decades of dispute between royal officials and local lords over which land falls under Forest Law. By the Great Disafforestation of 1300 (Edward I), the forest's legal extent is substantially reduced to its more familiar medieval footprint.",
    tags: ["royal", "commons"],
    era: "medieval",
    conflict: true,
    source: "Sherwood Forest History (World Anvil synthesis)",
    sourceUrl: "https://www.worldanvil.com/w/fabula-mundi-barwickian/a/sherwood-forest-organization"
  },
  {
    id: 10,
    year: 1290,
    yearLabel: "1290",
    title: "Parliament Oak: Edward I Holds Parliament in the Forest",
    body: "Edward I holds a parliament session at the Parliament Oak in Sherwood — a massive ancient tree near Clipstone still standing today. This underscores the forest's dual role: simultaneously a site of royal pleasure and royal governance. The Clipstone palace (Kings Clipstone) is a major royal hunting lodge, used repeatedly by Plantagenet kings.",
    tags: ["royal"],
    era: "medieval",
    conflict: false,
    source: "Ancient Odysseys",
    sourceUrl: "https://www.ancientodysseys.com/post/the-archaeology-of-sherwood-forest"
  },
  {
    id: 11,
    year: 1337,
    yearLabel: "1337",
    title: "Robin Hood First Named in Writing",
    body: "William Langland's <em>Piers Plowman</em> (c. 1377, earlier version ~1337) has the character Sloth confess: <em>\"I do not know my paternoster perfectly as the priest sings it but I know the rhymes of Robin Hood.\"</em> This is the first certain literary reference, confirming Robin Hood was a widespread popular legend by the mid-14th century — rooted in real forest-law grievances of the 12th–13th centuries.",
    tags: ["robin-hood"],
    era: "medieval",
    conflict: false,
    source: "Edwinstowe Historical Society",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/"
  },
  {
    id: 12,
    year: 1336,
    yearLabel: "1336",
    title: "Charcoal License: Henry de Edwinstowe",
    body: "Henry de Edwinstowe, vicar of Edwinstowe, is granted a royal licence to take trees from the forest to make 100 quarters of charcoal — a significant grant that illustrates how the forest continued to serve local economic needs even under Forest Law, and how clergy and gentry could obtain formal access to resources the poor accessed only through custom.",
    tags: ["commons"],
    era: "medieval",
    conflict: false,
    source: "Edwinstowe Historical Society — Trees",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/trees-sherwood-forest/"
  },
  {
    id: 13,
    year: 1400,
    yearLabel: "14th–15th c.",
    title: "Forest Outlaws: Real Precedents for the Legend",
    body: "Sherwood Forest Eyre court records (surviving from 1287 and 1334) document real outlaws produced by forest law. In 1267, John de Lascelles catches two men with bows and arrows. Roger Godberg is outlawed for involvement in the 2nd Barons' War (1264–67) and takes to the forest. The Coterel gang operates throughout the region in the 1320s–40s. These real cases establish that the outlawry depicted in Robin Hood tales was not fantasy but a documented social phenomenon.",
    tags: ["robin-hood", "commons"],
    era: "medieval",
    conflict: true,
    source: "Sherwood Forest History Blog — Outlaws",
    sourceUrl: "https://sherwoodforesthistory.blogspot.com/p/outlaws-villains.html"
  },
  {
    id: 14,
    year: 1485,
    yearLabel: "1485–1600",
    title: "Tudor Era: Felling for Shipbuilding &amp; Agriculture",
    body: "Under the Tudors, Sherwood's timber becomes a national strategic resource. Oak is felled for the building of Henry VIII's navy. Increasing agricultural clearance converts forest margins to pasture and arable land. Villages and townships expand. The forest landscape — once described as so dense that branches intermingled — begins to open up dramatically through the 16th century.",
    tags: ["enclosure", "industry"],
    era: "tudor",
    conflict: false,
    source: "Edwinstowe Historical Society — Trees",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/trees-sherwood-forest/"
  },
  {
    id: 15,
    year: 1609,
    yearLabel: "1609",
    title: "Final Major Perambulation — Boundaries Shrinking",
    body: "A 1609 perambulation confirms the forest's boundaries have continued to contract from their medieval maximum. James I's commissioners begin investigating unprofitable royal forests as sources of potential revenue through sale or enclosure — Sherwood is assessed but retained for the time being. The process of converting forest jurisdiction to private estate management accelerates across the Stuart period.",
    tags: ["royal", "enclosure"],
    era: "tudor",
    conflict: false,
    source: "Sherwood Forest History (World Anvil synthesis)",
    sourceUrl: "https://www.worldanvil.com/w/fabula-mundi-barwickian/a/sherwood-forest-organization"
  },
  {
    id: 16,
    year: 1674,
    yearLabel: "1674–1700",
    title: "Crown Sells &amp; Grants Sherwood Lands to Nobles",
    body: "By the later 17th century, large areas of Crown land in Sherwood are sold or gifted to court favourites and nobles. The foundations of the great Dukeries estates — Thoresby, Welbeck, Clumber, Rufford, Newstead — are laid. These private landlords bring new estate-management regimes: enclosing commons, planting timber for profit, creating ornamental parkland, and excluding customary users.",
    tags: ["enclosure", "royal"],
    era: "tudor",
    conflict: true,
    source: "Nottinghamshire County Council",
    sourceUrl: "https://www.nottinghamshire.gov.uk/culture-leisure/country-parks/history-of-sherwood-forest-robin-hood-and-major-oak"
  },
  {
    id: 17,
    year: 1740,
    yearLabel: "Mid-18th century",
    title: "Edwinstowe Poor: Firewood &amp; Fern Rights",
    body: "As late as the mid-18th century, the poor residents of Edwinstowe <em>\"could supply themselves plentifully with firewood, during the whole year\"</em> from the forest remnant. Ferns (bracken) were gathered and burned to produce ash for soap-making lye — a crucial household industry. These customary rights of <em>firebote</em> coexisted alongside the enclosing estates, increasingly contested and precarious.",
    tags: ["commons"],
    era: "georgian",
    conflict: true,
    source: "Magna Carta 800th Trust",
    sourceUrl: "https://magnacarta800th.com/papers/forests-the-magna-carta-and-the-new-commons-some-thoughts-for-the-forest-panel/"
  },
  {
    id: 18,
    year: 1750,
    yearLabel: "1750–1830",
    title: "The Dukeries: Aristocratic 'Improvement' &amp; Enclosure",
    body: "Georgian 'improvement' ideology transforms Sherwood. The great ducal estates — by the 1870s, one family alone owned 43,000 Nottinghamshire acres — enclose and landscape former common land. Humphry Repton redesigns parkland. Commoners are expelled from areas their ancestors had used for centuries. The Cambridge Rural History journal documents this as a period of intense 'contestation' — owners attempting to 'keep unwanted plebeian incursions at bay.'",
    tags: ["enclosure", "commons"],
    era: "georgian",
    conflict: true,
    source: "Cambridge Core — Patrician Landscapes",
    sourceUrl: "https://www.cambridge.org/core/journals/rural-history/article/patrician-landscapes-and-the-picturesque-in-nottinghamshire-c1750c1850/19ACEF1C132ED92D3457FE03F106A296"
  },
  {
    id: 19,
    year: 1787,
    yearLabel: "1787–1793",
    title: "Royal Commission Reports: Sherwood 'Produces No Profit'",
    body: "A Royal Commission investigating Crown woods publishes 17 reports. Of Sherwood, it concludes: <em>\"No Deer being now kept for the King in any Part of the Forest, except Thorney Woods, the Forestrial Rights are productive of no Profit or Advantage.\"</em> This strips away the last rationale for maintaining it as a functioning royal forest and accelerates moves toward full disafforestation and sale.",
    tags: ["royal", "enclosure"],
    era: "georgian",
    conflict: false,
    source: "Robin Hood Legend — Forests After Restoration",
    sourceUrl: "https://robinhoodlegend.com/forests-restoration/"
  },
  {
    id: 20,
    year: 1818,
    yearLabel: "1818",
    title: "Disafforestation Act: End of the Royal Forest",
    body: "An Act of Parliament formally disafforests Sherwood — ending over 750 years of royal forest status. The legal framework of Forest Law, under which deer and timber were royal property and commons were conditionally tolerated, is abolished. This is simultaneously a liberation from a feudal legal regime and the final act of enclosure: common rights, which had persisted partly because Forest Law recognised them, are now fully extinguished.",
    tags: ["enclosure", "royal"],
    era: "georgian",
    conflict: false,
    source: "Sherwood Forest History (World Anvil synthesis)",
    sourceUrl: "https://www.worldanvil.com/w/fabula-mundi-barwickian/a/sherwood-forest-organization"
  },
  {
    id: 21,
    year: 1830,
    yearLabel: "c. 1830",
    title: "Last Crown Lands at Birklands &amp; Bilhaugh Sold",
    body: "By around 1830, even the remaining Crown-held parcels at Birklands and Bilhaugh near Edwinstowe — the very last of the original royal forest in Crown ownership — are sold. The transformation from common royal resource to divided private property is now complete. The ancient oaks of Birklands survive only because they are already too gnarled and hollow to be worth commercial felling.",
    tags: ["enclosure"],
    era: "georgian",
    conflict: true,
    source: "Nottinghamshire County Council",
    sourceUrl: "https://www.nottinghamshire.gov.uk/culture-leisure/country-parks/history-of-sherwood-forest-robin-hood-and-major-oak"
  },
  {
    id: 22,
    year: 1850,
    yearLabel: "Mid-19th century",
    title: "Romantic Revival: Robin Hood &amp; Victorian Tourism",
    body: "Sir Walter Scott and other Romantic-era authors popularise Sherwood and Robin Hood for a national and international audience. Victorian tourism brings visitors to the Major Oak. The forest is simultaneously being destroyed by industry while being mythologised as 'Merrie England.' The romantic image of outlaws fighting for the poor becomes a cultural touchstone — and masks the ongoing dispossession of common rights.",
    tags: ["robin-hood"],
    era: "victorian",
    conflict: false,
    source: "Historic UK — Sherwood Forest",
    sourceUrl: "https://www.historic-uk.com/HistoryMagazine/DestinationsUK/Sherwood-Forest/"
  },
  {
    id: 23,
    year: 1860,
    yearLabel: "1860–1900",
    title: "Coal Mining Opens the East Nottinghamshire Coalfield",
    body: "The great era of Nottinghamshire coal mining begins. Collieries at Clipstone, Thoresby, Ollerton, and across the 'dukeries' coalfield bring thousands of workers, building new towns directly on former forest margins. Mining subsidence, rail infrastructure, roads, and the need for pit-prop timber compound the forest's losses. The area's ancient ecology begins its steepest decline.",
    tags: ["industry", "enclosure"],
    era: "victorian",
    conflict: false,
    source: "Edwinstowe Historical Society",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/"
  },
  {
    id: 24,
    year: 1914,
    yearLabel: "1914–1918",
    title: "World War I: Military Requisition",
    body: "Areas of Sherwood are requisitioned for military use — camps, training grounds, and logistics. Timber is urgently felled for the war effort. The demands of industrial warfare accelerate pre-existing woodland losses. The local ecosystem faces compounding stress from military clearance and the general wartime suspension of normal land management.",
    tags: ["industry"],
    era: "victorian",
    conflict: false,
    source: "Edwinstowe Historical Society",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/"
  },
  {
    id: 25,
    year: 1939,
    yearLabel: "1939–1945",
    title: "World War II: Ammunition Stores &amp; POW Camps",
    body: "During WWII, Sherwood Forest is requisitioned for CAD Warsop (Central Ammunition Depot), military training, prisoner-of-war camps, and camps for displaced persons. The national demand for softwood timber transforms surviving portions with conifer plantations. By war's end, the landscape bears little resemblance to the historic mixed oak and birch woodland.",
    tags: ["industry"],
    era: "victorian",
    conflict: false,
    source: "Edwinstowe Historical Society",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/"
  },
  {
    id: 26,
    year: 1960,
    yearLabel: "1960s–1970s",
    title: "Urban Sprawl &amp; the Forest Shrinks to a Fragment",
    body: "Post-war suburbanisation and continued industrial development from Nottingham, Mansfield, Worksop, and Kirkby-in-Ashfield consume the forest margins. Road construction, housing estates, and retail development eat into even degraded woodland. By the mid-20th century, the original Sherwood of 100,000+ medieval acres has been reduced to scattered fragments totalling perhaps 450–500 hectares of genuinely ancient woodland.",
    tags: ["industry", "enclosure"],
    era: "victorian",
    conflict: false,
    source: "Nottinghamshire County Council",
    sourceUrl: "https://www.nottinghamshire.gov.uk/culture-leisure/country-parks/history-of-sherwood-forest-robin-hood-and-major-oak"
  },
  {
    id: 27,
    year: 1977,
    yearLabel: "1977",
    title: "Grade 1 Conservation Classification",
    body: "A Nature Conservation Review classifies the 200-hectare Sherwood Forest Country Park as a Grade 1 area of ancient woodland and heathland — the highest conservation category. This is the first formal recognition of the surviving woodland's national ecological significance, setting the stage for subsequent statutory protections.",
    tags: ["conservation"],
    era: "contemporary",
    conflict: false,
    source: "Eakring Birds — Sherwood NNR",
    sourceUrl: "http://www.eakringbirds.com/eakringbirds6/sherwoodforestinvertebrates.htm"
  },
  {
    id: 28,
    year: 1981,
    yearLabel: "1981",
    title: "SSSI Designation — Wildlife &amp; Countryside Act",
    body: "The Birklands and Bilhaugh complex is designated as a Site of Special Scientific Interest (SSSI) under the 1981 Wildlife and Countryside Act. The site's 1,000+ veteran oaks — supporting an exceptional community of saproxylic (dead-wood dependent) invertebrates, including species found nowhere else in the UK — form the basis of the designation. The ancient oaks survived only because they were too gnarled to fell commercially.",
    tags: ["conservation"],
    era: "contemporary",
    conflict: false,
    source: "Eakring Birds — Sherwood NNR",
    sourceUrl: "http://www.eakringbirds.com/eakringbirds6/sherwoodforestinvertebrates.htm"
  },
  {
    id: 29,
    year: 2002,
    yearLabel: "2002",
    title: "National Nature Reserve Status",
    body: "Sherwood Forest is designated a National Nature Reserve (NNR) — the UK's highest nature conservation status. The NNR encompasses the Sherwood Forest Country Park and Budby South Forest, representing the core of the surviving ancient woodland. Natural England manages the site. The reserve holds the highest concentration of ancient trees in Europe.",
    tags: ["conservation"],
    era: "contemporary",
    conflict: false,
    source: "Edwinstowe Historical Society",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/"
  },
  {
    id: 30,
    year: 2007,
    yearLabel: "2007",
    title: "Major Oak Replanting — Sherwood Renewal",
    body: "A ceremonial Major Oak replanting takes place on 10 August 2007, symbolising the commitment to Sherwood Forest's future. Partners including the Sherwood Forest Trust, Natural England, and Nottinghamshire County Council accelerate heathland restoration — removing non-native conifer plantations, restoring bracken-free ground flora, and planning ecological corridors to reconnect surviving woodland patches. This marks the transition from passive protection to active rewilding.",
    tags: ["conservation"],
    era: "contemporary",
    conflict: false,
    source: "Edwinstowe Historical Society — Trees",
    sourceUrl: "https://edwinstowehistory.org.uk/local-history/sherwood-forest/trees-sherwood-forest/"
  },
  {
    id: 31,
    year: 2020,
    yearLabel: "2020s",
    title: "Sherwood Forest Trust &amp; Heathland Restoration",
    body: "Ongoing partnership-led restoration continues into the 2020s. The Forestry Commission removes Pine plantations at Clipstone Old Quarter to restore heathland. The Sherwood Pines management team works on building 'resilient forests for the future.' Ecological surveys show remarkable species recovery — 371 invertebrate species new to the NNR recorded since 2000, alongside the rediscovery of the Hazel Pot Beetle (absent for 70+ years) in 2008 and the Welsh Clearwing moth.",
    tags: ["conservation"],
    era: "contemporary",
    conflict: false,
    source: "Eakring Birds — Sherwood NNR",
    sourceUrl: "http://www.eakringbirds.com/eakringbirds6/sherwoodforestinvertebrates.htm"
  }
];
